### ISSUE TITLE
Add support for `__vec2x32float__` arguments

### ISSUE THREAD

**Issue by muff1n1634** [encounter/cwdemangle#2]
Metrowerks mangles these as the character `2`.

I came across a function that was mangled as `sincosf_f__F2`, and noticed that at its callsite it was flanked by `ps_mr` instructions:
```asm
    ps_mr   f1, f31
    bl      sincosf_f__F2
    ps_mr   f30, f1
```

and [some testing](https://decomp.me/scratch/LousU) shows that this is the mangled name of the function signature `sincosf_f(__vec2x32float__)`.

Currently cwdemangle demangles this as `sincosf_f(2)`.

**Comment by encounter** [comment]
This will be available in version 0.2.0 with the flag `--mw-extensions`.
